# -*- coding: utf-8 -*-
"""Histogram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16rYdc7tM59VPtrsQJgFci4YLmlsTwmxV
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('apple.jpeg',0) #bu yöntem, belirtilen dosyadan yüklenen bir görüntüyü döndürür.
cv2_imshow(img) #Görüntülenmesi gereken görüntüdür.
plt.hist(img.ravel(),256,[0,256]);  #Ekranda gösterilecek grafik değerlerinin hangi alanda olacağı ve görüntüyü bu aralığa alma.
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()