# -*- coding: utf-8 -*-
"""histogram denklestirme.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RTB1TW3uIsAEppSYLBxszzXNupwFrJeI
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow

img=cv2.imread('apple.jpeg',0)
h_img=cv2.equalizeHist(img) #Histogram denkleştirme fonksiyonu
cv2_imshow(np.hstack((img,h_img))) 
plt.hist(img.ravel(),256,[0,256]);  #Ekranda gösterilecek grafik değerlerinin hangi alanda olacağı ve görüntüyü bu aralığa alma.
plt.show()
plt.hist(h_img.ravel(),256,[0,256]);  
plt.show()