# -*- coding: utf-8 -*-
"""salt-and-pepper(noise-histogram).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q85PS2KOWoJ1lM-nspGiKWRwqZFmPRov
"""

import random
import cv2
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow
 
def add_noise(img):
 
    
    row , col = img.shape
     
    number_of_pixels = random.randint(300, 10000)
    for i in range(number_of_pixels):
       
        # Random y koordinatı alınır.
        y_coord=random.randint(0, row - 1)
         
        # Random x koordinatı alınır.
        x_coord=random.randint(0, col - 1)
         
        img[y_coord][x_coord] = 255
         

    number_of_pixels = random.randint(300 , 10000)
    for i in range(number_of_pixels):
       
        # Random y koordinatı alınır.
        y_coord=random.randint(0, row - 1)
         
        # Random x koordinatı alınır.
        x_coord=random.randint(0, col - 1)
         
        img[y_coord][x_coord] = 0
         
    return img
 
img = cv2.imread('apple.jpeg',0)
cv2_imshow(img)
#Görüntüyü Kaydetme
cv2.imwrite('salt-and-pepper-noise.jpg',add_noise(img))

noise_img=cv2.imread('salt-and-pepper-noise.jpg')
cv2_imshow(noise_img)

plt.hist(img.ravel(),256,[0,256]);  #Ekranda gösterilecek grafik değerlerinin hangi alanda olacağı ve görüntüyü bu aralığa alma.
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()