# -*- coding: utf-8 -*-
"""Bit Degistirme.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13W2HcrAF_EpVz-O_uSNt5ySIW4bUD5Ks
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow

# Resmi yükleme
img = cv2.imread('apple.jpeg',cv2.IMREAD_GRAYSCALE)

img8=img/(255/8)
img16=img/(255/16)
img24=img/(255/24)

cv2_imshow(np.hstack((img,img8,img16,img24)))

plt_org=plt.hist(img.ravel(),256,[0,256]);
plt_8=plt.hist(img8.ravel(),256,[0,256]);
plt_16=plt.hist(img16.ravel(),256,[0,256]);
plt_24=plt.hist(img24.ravel(),256,[0,256]);