# -*- coding: utf-8 -*-
"""make-soft.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q85PS2KOWoJ1lM-nspGiKWRwqZFmPRov
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
 
img = cv2.imread('blur.png',1) 
img1 = cv2.blur(img,(5,5)) # Elimizdeki görüntüyü bulanıklaştırıyoruz.
img2 = cv2.boxFilter(img,-1,(2,2),normalize=True) # Filtre lullanarak bu görüntüyü yumuşatıyoruz.

cv2_imshow(np.hstack((img1,img2)))