# -*- coding: utf-8 -*-
"""Negatifini alma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13W2HcrAF_EpVz-O_uSNt5ySIW4bUD5Ks
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Resmi yükleme
img = cv2.imread('apple.jpeg')

# Görüntünün değeri max gray seviyeden çıkarılır egatif elde edilir
img_neg = 255 - img
cv2_imshow(np.hstack((img,img_neg)))