# -*- coding: utf-8 -*-
"""Matris (Görüntü) Oluşturma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16rYdc7tM59VPtrsQJgFci4YLmlsTwmxV
"""

import numpy as np
from matplotlib import pyplot as plt

row = 256
col = 256 
img = np.zeros((row,col))
img[100:105, :] = 0.5
img[:, 100:105] = 1

plt.figure(figsize=(10,4))
plt.imshow(img)
plt.show()