# -*- coding: utf-8 -*-
"""Logaritmik Donusum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13W2HcrAF_EpVz-O_uSNt5ySIW4bUD5Ks
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
# Load the image
img = cv2.imread('apple.jpeg')
c = 255 / np.log(1 + np.max(img)) 
img_log = c * (np.log(img + 1))
# Display the image
cv2_imshow(np.hstack((img,img_log)))